### ISSUE TITLE
Level Reporter

### ISSUE THREAD

**Issue by iamHuko** [zzyzzyzzx/Hadar#1]
When I leveled I got this message

Run-time error
Plugin: LevelReport (called from world: Aardwolf)
Immediate execution
[string "Timer: "]:1: attempt to index global 'LevelReportVariables' (a nil value)
stack traceback:
        [string "Timer: "]:1: in main chunk

I have the lua in the lua folder and xml in the normal xml.  I had an error when loading as well.

Run-time error
Plugin: LevelReport (called from world: Aardwolf)
Function/Sub: OnPluginSaveState called by Plugin LevelReport
Reason: Executing plugin LevelReport sub OnPluginSaveState
C:\Users\Adam\Downloads\AardNew\lua\serialize.lua:78: Variable 'LevelReportVariables' does not exist
stack traceback:
        [C]: in function 'assert'
        C:\Users\Adam\Downloads\AardNew\lua\serialize.lua:78: in function 'save'
        [string "Plugin: LevelReport"]:241: in function <[string "Plugin: LevelReport"]:240>
        [C]: in function 'SaveState'
        [string "Plugin: LevelReport"]:465: in function <[string "Plugin: LevelReport"]:454>

**Comment by zzyzzyzzx** [comment]
Did commit #691d283 fix it?

**Comment by iamHuko** [comment]
yep!@
