### ISSUE TITLE
identify: help run-time error

### ISSUE THREAD

**Issue by altere987** [zzyzzyzzx/Hadar#12]
I mis-typed and put "hid help help2" instead of 'hid help 2' which results in a run-time error.

1362
Run-time error
Plugin: Hadars_identify (called from world: Aardwolf)
Function/Sub: hidMain called by alias
Reason: processing alias ""
.\worlds\plugins\aardwolf_colors.lua:599: attempt to index local 'text' (a nil value)
stack traceback:
        .\worlds\plugins\aardwolf_colors.lua:599: in function 'ColoursToANSI'
        [string "Plugin: Hadars_identify"]:20: in function 'hadarprint'
        [string "Plugin: Hadars_identify"]:1198: in function 'HadarHelp'
        [string "Plugin: Hadars_identify"]:81: in function <[string "Plugin: Hadars_identify"]:67>

additionally 'hid help':
hid set - will let you hadarmagic the output, type hid help2 for a helpfile |
|           with all variables

Probably just add a space between help and 2, which is where my initial confusion came from.

**Comment by zzyzzyzzx** [comment]
just pushed an update to fix it, if you input a wrong message it will now just give you the main helpfile :)
