### ISSUE TITLE
Spellup Plugin

### ISSUE THREAD

**Issue by AardwolfScars** [zzyzzyzzx/Hadar#14]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
From    : Scars: SpellUp Plugin Enhancements
Forum   : Personal - #318744
To      : Scars hadar
Date    : Thu Dec 31 15:44:18 2020
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Note #291889 originally posted to : Crowley
| Note forwarded by         : Scars on Thu Dec 31 15:44:18 2020
| Hey Crowley,
| 
| Thanks for even remotely entertaining this.
| 
| There are 3 things I think that WinkleWinkle's (can't comment on Bast)
| spellup plug in doesn't seem to address very effectively.
| 1. Managing the "wear aura" versus "cast sanctuary/biofeedback" situation.
| 2. Managing recovery timer versus affected by spells/skills.
| 3. Spell order of wraith form and wolf spirits.
| 
| Expanding on #1, which I'll arbitrarily decide to call: AutoAura.
| I think this is pretty straightforward, but for the sake of making
| sure we're talking about the same thing, I'll be more verbose than I think
| is necessary.
| 
| Sometimes, notably at SH, there are a number of float items that are
| better stats than the Aardwolf Aura of Sanctuary. Ideally, to
| maximize the value of the item, you would wear the float item and cast
| sanctuary. However, when in combat, you could be dispelled. You'd want to
| quickly (automatically) wear the Aardwolf Aura of Sanctuary during
| combat. Upon exiting combat, you'd remove the Aardwolf Aura of
| Sanctuary and cast sanctuary per usual.
| 
| As a special circumstance, you may want to REQUIRE than the aura be worn,
| so disabling the AutoAura script. That may be for raids, epics, whatever.
| 
| Expanding on #2, which I will needlessly call: RecoveryManager:
| Many subclass skills are subject to recovery timers that do not line up
| with their duration. Because of this, we have to do a bit of "can I cast
| this spell yet" check in or randomly initiate a spellup to make sure
| things like power projection or ironfist or whatever are up. With the new
| totems out there now, this feels like so much unnecessary micromanagement
| that passive monitoring would really help simplify.
| 
| I (now) know you hate miniwindows, but my idea was having something that
| showed an abbreviated / modified version of what's shown on using the
| "affected" command. In this miniwindow, all recovery oriented skills that
| are available to the player are shown. 
| The display has 3 scenarios:
| CASE | AFFECTED  | ON RECOVERY | COLOR
| #1        Y             Y      green
| #2        N             Y      yellow
| #3        N             N      white
| 
| I suppose for an added feature, on top of this, players could identify
| which of the skills/spells they want to auto-cast when available. That
| would ensure things that are mutually exclusive like rage/ironfist behave
| in an expected manner. Also, a way to ensure that the auto-cast uses the
| required "selection" for these gems:
| cast 'elemental focus' [air|earth|fire|water]
| cast 'elemental ward' [air|earth|fire|water]
| cast 'gaias focus' [air|earth|electric|cold|water]
| cast 'gaias totem' [ent|bear|owl]
| There may be more, but these are the one's that I know.
| 
| Expanding on #3, which I'll needlessly call SmartCast.
| Wraith Form, Wolf Spirits and any other spells that give affects that are
| covered by other spells, should be cast after them. For example, sneak
| should always be before wraith form. This isn't a big deal to me, but I
| thought I'd share it anyway.
| 
| Anyway, there you have it. That's what's on my mind!
| Thanks,
| Scars
| 
|
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by zzyzzyzzx** [comment]
Pushed to production, closing this idea, anything else needed to be done needs a new issue
