### ISSUE TITLE
repop plugin dies on repop

### ISSUE THREAD

**Issue by Shindo-Aardwolf** [zzyzzyzzx/Hadar#15]
`Run-time error
Plugin: Hadar_Repop (called from world: Aardwolf)
Function/Sub: OnPluginBroadcast called by Plugin Hadar_Repop
Reason: Executing plugin Hadar_Repop sub OnPluginBroadcast
[string "Plugin: Hadar_Repop"]:16: attempt to index local 's' (a nil value)
stack traceback:
        [string "Plugin: Hadar_Repop"]:16: in function 'interp'
        [string "Plugin: Hadar_Repop"]:89: in function <[string "Plugin: Hadar_Repop"]:72>`

It worked before I updated via hpm check then straight after gives the above error

**Comment by zzyzzyzzx** [comment]
You are going to want to reset the message. I need to see why it is dieing on update. Just do a repopset the default message is

@W${name} @Cr@cepoped @Ca@ct @R${hour}@w:@R${min}@w

I see the error I'll fix it tomorrow when I get home from work I'm going to bed

**Comment by Shindo-Aardwolf** [comment]
Are you not using the gmcp repop mechanism?
`comm.repop { "zone": "aylor" }`
[Aardwolf GMCP stuffs](http://www.aardwolf.com/wiki/index.php/Clients/GMCP)

**Comment by zzyzzyzzx** [comment]
no, one of my variables was misnamed i pushed the fix for it so it should not happen anymore :) -closing if anymore issues let me know :)

**Comment by Shindo-Aardwolf** [comment]
Still doing it... 
First line is our clan repop message

`A holy light ripples across Touchstone Cavern and new life is born.
Run-time error
Plugin: Hadar_Repop (called from world: Aardwolf)
Function/Sub: OnPluginBroadcast called by Plugin Hadar_Repop
Reason: Executing plugin Hadar_Repop sub OnPluginBroadcast
[string "Plugin: Hadar_Repop"]:16: attempt to index local 's' (a nil value)
stack traceback:
        [string "Plugin: Hadar_Repop"]:16: in function 'interp'
        [string "Plugin: Hadar_Repop"]:89: in function <[string "Plugin: Hadar_Repop"]:72>`

**Comment by zzyzzyzzx** [comment]
use the command:

setrepop

when the dialogbox pops up put this inside it:

@W${name} @cr@cepoped @ca@ct @r${hour}@w:@r${min}@w
