### ISSUE TITLE
useful plugin but needs fixed

### ISSUE THREAD

**Issue by Khrysis-aard** [zzyzzyzzx/Hadar#16]
https://github.com/Shindo-Aardwolf/Mushclient-Consider

it doesn't seem to grab the auras into the mini window it just shows a blank black spot where they are suppose to be added
and the list in the mini window is no longer clickable like the older versions of this plugin are
if u can look at it when u get a chance or even have a different version of this it would be awesome
also needs updated to include where if multiples of the same mob will do 2.mob 3.mob etc

**Comment by Khrysis-aard** [comment]
ok fixed the clickable window part

execute_command in Show_window function needs to be Execute_command instead

far as the flags prob i am not sure though

**Comment by Khrysis-aard** [comment]
function Process_flags (flags)
	local newflags = ''
	if string.find(flags,"%(W%)") or
           string.find(flags,"%(White Aura%)") then
		newflags = newflags.. "@x015(W)"
	else
		newflags = newflags.. "   "
	end
	if string.find(flags,"%(R%)") or
           string.find(flags,"%(Red Aura%)") then
		newflags = newflags.. "@x001(R)"
	elseif string.find(flags,"%(G%)") or
               string.find(flags,"%(Golden Aura%)") then
		newflags = newflags.. "@x003(G)"
	else
		newflags = newflags.. "   "
	end

	return newflags
end

Fix for the flags on it as well it required short flags to be on to work.
Now it will work either way and output short flags in the miniwin
Still interested to see what you come up with for this plugin when u get around to it.

**Comment by zzyzzyzzx** [comment]
shindo still active not taking on project
