### ISSUE TITLE
LevelReport Ideas

### ISSUE THREAD

**Issue by iamHuko** [zzyzzyzzx/Hadar#2]
Mute the command/echo or whatever it is that sends the message to the channel.

channel?gt
report?@GL@gevel@R(@w107@R) @GT@gook:@w[@GH:@W0 @GM:@W0 @GS:@W1@w] @GH@gP@R(@w34@R)@GM@gn@R(@w31@R)@GM@gv@R(@w21@R)@GP@gr@R(@w12@R)@GT@gr@R(@w6@R)@G +@gStats:@wDex@w

Make it a nice little spiffy screen similar to what is muted from the game. 

and Option to turn off the channel message and just get the spiffy screen similar to what is muted from the game.

**Comment by zzyzzyzzx** [comment]
This has been fixed in the latest push, along with a new command added, levelshow <level> <channel>
