### ISSUE TITLE
spellup issues.

### ISSUE THREAD

**Issue by lightsrage** [zzyzzyzzx/Hadar#24]
So the spellup plugin likes to give  me errors like affoff runtime error  and saff and then I have to reinstall the plugin about every 20 minutes to get the plugin working about. I am using the vi package  and not much else at this point. I was using some others but redid my package to see if that was the issue. and yet it persists. can you assist.

**Comment by zzyzzyzzx** [comment]
were you still having this issue? or did i ever resolve it?

**Comment by lightsrage** [comment]
The one where it tried to like do something with a null value yes. All the time I constantly have to reinstall the plugin to get it working. The error message is long and I often cant find it in all the text to paste it I haven’t been on in a while because I got a new job and things have been insane. I am going to try and play this weekend.

**Comment by zzyzzyzzx** [comment]
When you come back, make sure its the newest version of the spellup plugin, and ill wait to hear if there was any issues!

hope to hear back from you soon!

**Comment by lightsrage** [comment]
I will check into it. I logged in but did not hear of plugin updates but will check the next time I log in. Yeah have a good weekend. I just got off work and am beat. First weeks suck.

**Comment by zzyzzyzzx** [comment]
thinking this was part of the gaias revenge bug pr #43 fixed it, make sure you update
