### ISSUE TITLE
Spellup not spelling up

### ISSUE THREAD

**Issue by Anssett** [zzyzzyzzx/Hadar#35]
https://l33t.xyz/aardbin/7ffb656
not respelling even with newest version, reinstalled the plugin, verified that auto spellup is enabled.

**Comment by Anssett** [comment]
Update: after another half-dozen toggling of hsp disable off and on, things are recasting properly again. Wat. Will update if it reverts.

**Comment by zzyzzyzzx** [comment]
Hrmmm did you toggle on the new feature? Or what did you do so I can try to recreate?

**Comment by Anssett** [comment]
No new features that weren't enabled by updating. Did the first full spellup of the mort, ran oom, slept, woke up, recasted, slept, and then noticed spells were not recasting. max mana didn't help. tried adjusting the hsp percent percentage to a different value, didn't help. 
Uninstalled hsp, reinstalled it, reloaded, relaunched mushclient, none of these had an obvious effect. idly started toggling hsp disable out of annoyance, saw cskill recast, then all of a sudden everythign else was recasting too. unsure if it was because of cskill recasting, or the toggling, or something else that i just didn't see happen.
Was at max mana most of this time.

**Comment by zzyzzyzzx** [comment]
I wonder if you got hit with the new skill cast while no mana thing I wrote I'll check it out later.  There is also a toggle if it happens again. That or when you remorted something happened with the auto disable and auto enable again something I'll check out when I have computer time

**Comment by Anssett** [comment]
I generally have 3-4 spells that i cast and up to that point they were recasting fine. SOmething about going OOM seems to have gone wonky.

**Comment by Anssett** [comment]
More details that may be helpful:
https://l33t.xyz/aardbin/777b7a4

recap: went oom, spellup disabled. regenned mana, spellup did not fire. manually spelled up. toggled hsp disable off and on. spellup did not fire. toggled hsp disable off and on 2x more, spellup fired.

**Comment by zzyzzyzzx** [comment]
looks like the new code, when it happens again try hsp disable disablespellsoff

see if that fixes it, if it does i know the issue, if not ill have to dig more

**Comment by Anssett** [comment]
cancel
respell triggered
ran oom, plugin showed recast disabled
regenned full mana
spellup manually
disrupt individual spell, no recast
hsp disable check says [Spellup] Spellup Autocast is currently ENABLED
cancel, no respell
hsp disable disablespellsoff gives no feedback
disrupt individual spell, recasts
cancel
respell triggered

Looks like the plugin needs to detect when adequate mana has regenned and run hsp disable disablespellsoff. and probably need to document that particular command. Or at least mention it in the OOM casting message.

Anyway that's my thoughts. Working, but only if you know hsp disable disablespellsoff :)

-Ans

**Comment by zzyzzyzzx** [comment]
Thanks for that, i know what the issue is, its trying to do 2 different things, the document from hsp disable <whatever> is never ment to be used, i use it in the script to enable/disable stuff and for the most part they are ment to be silent, but i know what the issue is, it is caused from my change to the way OOM casts happen now, since i added a way to use skills while OOM, will fix in a bit
