### ISSUE TITLE
New Project - xRoutes Extender

### ISSUE THREAD

**Issue by tallimos** [zzyzzyzzx/Hadar#7]
xRoutes is a command that is available via the WinkleGold Mapper Extender plugin. It is a very useful but limited command. Its sole purpose is to display the speedwalks from your current location to all areas that have a starting room set. (i.e. xset mark - which is probably another part of the extender plugin).

Extended Version
   - display speedwalks that have a certain amount of steps, certain range, etc.. i.e 10 or more, between 5 and 9 etc...
   - display speedwalks to areas with certain level ranges
   - display speedwalks to a specific area
   - display all speedwalks for areas at certain levels since you have access to different portals at different levels
   - anything else that could be useful with this command

Reason for script: Useful for determining areas where speedwalks area really long and can be shorten with a portal or manor exit

**Comment by zzyzzyzzx** [comment]
i feel like you said you done need this anymore? let me know

**Comment by tallimos** [comment]
Nope I dont need
